apiVersion: v1
kind: ConfigMap
metadata:
  name: tenderops-api-config
  namespace: tenderops
data:
  SPRING_PROFILES_ACTIVE: local
  SPRING_DATASOURCE_URL: jdbc:postgresql://tenderops-db:5432/tenderops
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,metrics
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenderops-api
  namespace: tenderops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tenderops-api
  template:
    metadata:
      labels:
        app: tenderops-api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: tenderops-api:0.1.0
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: tenderops-api-config
            - secretRef:
                name: tenderops-api-runtime-secret
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: tenderops-api
  namespace: tenderops
spec:
  selector:
    app: tenderops-api
  ports:
    - port: 8080
      targetPort: 8080
